#!/usr/bin/env python3
import os
import sys

# 同じディレクトリの irumi.py を起動
current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, current_dir)

import irumi

if __name__ == "__main__":
    irumi.main()
